name: Pull Request
on:
  pull_request:
    branches:
      - master
      - alpha

env:
  RESOLVE_REGISTRY: https://repo.orl.eng.hitachivantara.com/artifactory/api/npm/npm/

jobs:
  License-Checks:
    name: License Checks
    runs-on: [self-hosted, Linux]
    container:
      image: node:12.14.1-buster
      options: -u 1000 # buildguy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: License Check
        run: npm run license-check

  Lint:
    runs-on: [self-hosted, Linux]
    container:
      image: node:12.14.1-buster
      options: -u 1000 # buildguy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

  Test-Jest:
    name: Test Jest
    runs-on: [self-hosted, Linux]
    container:
      image: node:12.14.1-buster
      options: -u 1000 # buildguy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Test
        run: npm run test

  Build-Documentation:
    name: Build Documentation
    runs-on: [self-hosted, Linux]
    container:
      image: node:12.14.1-buster
      options: -u 1000 # buildguy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Generate Documentation
        run: npm run build-documentation

      - name: Archive Documentation
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: dist

  Robot_pa11y:
    name: Test Robot pa11y
    needs: Build-Documentation
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PA11Y
        working-directory: ./automation/robot
        shell: cmd
        run: npm ci

      - name: Fetch Storybook
        uses: actions/download-artifact@v1
        with:
          name: documentation
          path: .github/storybook/www

      - name: Run Storybook
        uses: ./.github/storybook

      - name: Run PA11Y
        shell: cmd
        run: >-
          robot
          --variable STORYBOOK_URL:http://localhost:9002
          --include pa11y
          --outputdir reports
          --report report.html
          --log log.html
          automation\robot\storybook\core

      - name: Save Reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: pa11y-reports
          path: reports

  Robot:
    name: Test Robot
    needs: Build-Documentation
    runs-on: [self-hosted, Windows]
    timeout-minutes: 150
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Storybook
        uses: actions/download-artifact@v1
        with:
          name: documentation
          path: .github/storybook/www

      - name: Run Storybook
        uses: ./.github/storybook

      - name: Run SELENIUM Robot
        uses: ./.github/robot
        with:
          storybook-url: http://localhost:9002
          browser: ${{ matrix.browser }}
          excludes: |
            pa11y
            bug-${{ matrix.browser }}
            bug-${{ matrix.browser }}-webdriver
            issue
            issue-${{ matrix.browser }}
            bug-infrastructure
            bug-infrastructure-${{ matrix.browser }}
          output-dir: reports
          processes: 3
          path: ./automation/robot/storybook/core

      - name: Save Reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ${{ matrix.browser }}-reports
          path: reports
