name: v1.x Pull Request
on:
  pull_request:
    branches:
      - v1.x

# flow:
# License-Checks | Lint | Test-Jest | Build-Documentation
# Robot_pa11y | Robot (chrome)
# Notify End

env:
  RESOLVE_REGISTRY: https://repo.orl.eng.hitachivantara.com/artifactory/api/npm/npm/
  DOCUMENTATION_PUBLISH_REPO: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
  DOCUMENTATION_PUBLISH_BRANCH: master
  DOCUMENTATION_PUBLISH_FOLDER: uikit/pr-${{ github.event.number }}
  DOCUMENTATION_PUBLISH_MESSAGE: "docs: storybook for PR ${{ github.repository }}#${{ github.event.number }}"
  DOCUMENTATION_URL: https://${{ github.repository_owner }}.github.io/uikit/pr-${{ github.event.number }}/

jobs:
  Static-Checks:
    name: Licenses, Lint, Jest
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  Build-Documentation:
    name: Build Documentation
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Generate Documentation
        run: |
          npm run automation:package
          npm run build-documentation

      - name: Start Documentation Deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{env.DOCUMENTATION_PUBLISH_FOLDER}}
          ref: refs/pull/${{ github.event.number }}/head
          desc: ${{env.DOCUMENTATION_PUBLISH_FOLDER}}

      - name: Checkout Documentation Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DOCUMENTATION_PUBLISH_REPO }}
          ref: ${{ env.DOCUMENTATION_PUBLISH_BRANCH }}
          ssh-key: ${{ secrets.ORG_GHPAGES_DEPLOY_KEY }}
          path: gh-docs
          fetch-depth: 1

      - name: Copy Documentation to Repository
        run: |
          mkdir -p ./gh-docs/${DOCUMENTATION_PUBLISH_FOLDER}
          rm -rf ${{ github.workspace }}/gh-docs/${DOCUMENTATION_PUBLISH_FOLDER}/*
          cp -r packages/doc/dist/* ./gh-docs/${DOCUMENTATION_PUBLISH_FOLDER}

      - name: Push Documentation
        run: |
          cd ${{ github.workspace }}/gh-docs
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A ${DOCUMENTATION_PUBLISH_FOLDER}
          git commit -m "${DOCUMENTATION_PUBLISH_MESSAGE}"
          git pull --rebase
          git push

      - name: Cleanup Folder
        if: always()
        run: |
          rm -rf ${{ github.workspace }}/gh-docs

      - name: Archive Automation Storybook
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: automation/storybook/dist

      - name: Update Deployment Status
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{env.DOCUMENTATION_URL}}

  Robot:
    name: Test Robot
    needs: [Build-Documentation]
    runs-on: [self-hosted, Linux]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    container:
      image: joaoeg/docker-robot-framework:0.1
      options: --shm-size=6g --cpus 4 -u 2501
      env:
        BROWSER: ${{ matrix.browser }}
        ROBOT_TESTS_DIR: ./automation/robot/storybook/core
        ROBOT_REPORTS_DIR: ./reports
        ROBOT_THREADS: 4
        ROBOT_OPTIONS: "--variable STORYBOOK_URL:http://storybook --variable BROWSER:${{ matrix.browser }} --exclude pa11y --exclude bug-${{ matrix.browser }} --exclude bug-${{ matrix.browser }}-webdriver --exclude issue --exclude issue-${{ matrix.browser }} --exclude bug-infrastructure --exclude bug-infrastructure-${{ matrix.browser }}"

    services:
      storybook:
        image: nginx
        volumes:
          - ${{ github.workspace }}/dist:/usr/share/nginx/html
        options: >-
          --name storybook

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Storybook
        uses: actions/download-artifact@v1
        with:
          name: documentation
          path: ${{ github.workspace }}/dist

      - name: Restart nginx
        uses: docker://docker
        with:
          args: docker restart storybook

      - name: Run Robot
        run: ./.github/robot-docker/run-tests-in-virtual-screen-with-rerun.sh

      - name: Save Reports
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ${{ matrix.browser }}-reports
          path: reports

      - name: Clean Reports
        run: rm -rf reports

  Notify-End:
    name: Notify End
    needs: [Static-Checks, Build-Documentation, Robot]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: generate conclusion color
        id: conclusion_color
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if("${{ env.WORKFLOW_CONCLUSION }}" === "success") core.exportVariable("COLOR", "#63A621")
            else if("${{ env.WORKFLOW_CONCLUSION }}" === "failure") core.exportVariable("COLOR", "#C62828")
            else if("${{ env.WORKFLOW_CONCLUSION }}" === "neutral") core.exportVariable("COLOR", "#BCBCBC")
            else if("${{ env.WORKFLOW_CONCLUSION }}" === "cancelled") core.exportVariable("COLOR", "#FFD00A")
            else if("${{ env.WORKFLOW_CONCLUSION }}" === "timed_out") core.exportVariable("COLOR", "#FFD00A")

      - name: Notify
        uses: hbfernandes/slack-action@1.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CONCLUSION: ${{ env.WORKFLOW_CONCLUSION }}
        with:
          args: |
            {
              "channel": "ui-kit-eng-ci",
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "${{env.COLOR}}",
                  "title": "${{ github.workflow }} (${{github.ref}}) build finished - ${{ env.CONCLUSION }}",
                  "text": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                }
              ]
            }
